baseURL = "https://serendipitytours.com.au/"
languageCode = "en-us"
title = "Serendipity Tours Turkey"
theme = ""  # Leave empty if you're not using an external theme
enableRobotsTXT = true
googleAnalytics = "G-B8DN32CX3Z"  # Google Analytics ID here

[params]
  description = "Explore unforgettable journeys with Serendipity Tours."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true