baseURL = "http://serendipitytours.com.au/"
languageCode = "en-us"
title = "Serendipity Tours"
theme = ""  # Leave empty if you're not using an external theme
enableRobotsTXT = true

[params]
  description = "Explore unforgettable journeys with Serendipity Tours."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# Add this to your hugo.toml file
[services]
  [services.googleAnalytics]
    ID = "G-B8DN32CX3Z" # Replace with your actual measurement ID
    anonymizeIP = true # Privacy enhancement